# Generated by Django 3.0 on 2020-08-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_serv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=13)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=9)),
                ('opis', models.TextField(default='Proszę o dodanie opisu (opcjonalnie)', null=True)),
            ],
        ),
    ]
