# Generated by Django 3.0.1 on 2020-08-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=13)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=9)),
                ('ilosc', models.CharField(max_length=3)),
                ('opis', models.TextField(default='Zakup dla sklepu w innym przypadku zmień opis', null=True)),
            ],
        ),
    ]
